# Generated by Django 3.2.9 on 2021-12-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
