# Generated by Django 3.2.9 on 2021-12-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='optionA',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='optionB',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='optionC',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='optionD',
        ),
        migrations.AddField(
            model_name='questions',
            name='difficulty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('is_right', models.BooleanField()),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.questions', verbose_name='questions')),
            ],
        ),
    ]
