# Generated by Django 3.2.9 on 2021-12-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20211203_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='quiz'),
        ),
    ]
