# Generated by Django 3.2.9 on 2021-12-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='link',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
